export const mockTutors = [
  {
    id: 1,
    name: "Nguyễn Hà Anh",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=256&auto=format&fit=crop",
    title: "Giáo viên Tiếng Anh - IELTS 8.0",
    rating: 4.9,
    reviews: 124,
    subjects: ["Tiếng Anh", "IELTS", "Giao tiếp"],
    location: "Cầu Giấy, Hà Nội",
    hourlyRate: "250.000",
    isOnline: true,
    type: "Giáo viên",
  },
  {
    id: 2,
    name: "Trần Văn Nam",
    avatar: "https://images.unsplash.com/photo-1599566150163-29194dcaad36?q=80&w=256&auto=format&fit=crop",
    title: "Sinh viên năm 3 - Đại học Bách Khoa",
    rating: 4.8,
    reviews: 86,
    subjects: ["Toán", "Vật Lý", "Lớp 10-12"],
    location: "Quận 10, TP.HCM",
    hourlyRate: "150.000",
    isOnline: true,
    type: "Sinh viên",
  },
  {
    id: 3,
    name: "Lê Minh Tuấn",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=256&auto=format&fit=crop",
    title: "Cử nhân Sư phạm Toán",
    rating: 5.0,
    reviews: 210,
    subjects: ["Toán", "Luyện thi Đại học"],
    location: "Hải Châu, Đà Nẵng",
    hourlyRate: "300.000",
    isOnline: false,
    type: "Giáo viên",
  },
  {
    id: 4,
    name: "Phạm Phương Thảo",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?q=80&w=256&auto=format&fit=crop",
    title: "Sinh viên Ngoại Thương",
    rating: 4.7,
    reviews: 45,
    subjects: ["Tiếng Anh", "Ngữ Văn"],
    location: "Đống Đa, Hà Nội",
    hourlyRate: "120.000",
    isOnline: true,
    type: "Sinh viên",
  }
];

export const mockClasses = [
  {
    id: 1,
    title: "Tìm gia sư Toán lớp 10 cho con trai",
    parentName: "Chị Hoa",
    location: "Thanh Xuân, Hà Nội",
    subjects: ["Toán lớp 10"],
    format: "Offline",
    sessionsPerWeek: 2,
    budget: "150.000đ - 200.000đ / buổi",
    postedAt: "2 giờ trước",
    applicants: 3,
    status: "Đang tuyển",
  },
  {
    id: 2,
    title: "Cần giáo viên luyện thi IELTS 6.5 cấp tốc",
    parentName: "Anh Hoàng",
    location: "Toàn quốc",
    subjects: ["Tiếng Anh", "IELTS"],
    format: "Online",
    sessionsPerWeek: 3,
    budget: "300.000đ / buổi",
    postedAt: "5 giờ trước",
    applicants: 12,
    status: "Đang tuyển",
  },
  {
    id: 3,
    title: "Gia sư Rèn chữ, Tiếng Việt Lớp 2",
    parentName: "Cô Mai",
    location: "Quận 3, TP.HCM",
    subjects: ["Tiếng Việt", "Tiểu học"],
    format: "Offline",
    sessionsPerWeek: 3,
    budget: "100.000đ / buổi",
    postedAt: "1 ngày trước",
    applicants: 1,
    status: "Đang tuyển",
  },
  {
    id: 4,
    title: "Dạy kèm Lý Hóa lớp 12 luyện thi",
    parentName: "Chú Bình",
    location: "Toàn quốc",
    subjects: ["Vật Lý", "Hóa Học"],
    format: "Online",
    sessionsPerWeek: 2,
    budget: "250.000đ / buổi",
    postedAt: "1 ngày trước",
    applicants: 5,
    status: "Đang tuyển",
  }
];
